version: '3.9'
services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7.44
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "database"
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  web_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_service
    restart: always
    ports:
      - "8020:8020"
    depends_on:
      mysql:
        condition: service_healthy
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    environment:
      HTTP_HANDLER_PORT: 8020
      DB_ADDRESS: mysql:3306
      GIN_MODE: release
      WORKDIR: /app/
    healthcheck:
      test:  netstat -ltn | grep -c 8020
      interval: 600s
      timeout: 10s
      retries: 5
      start_period: 2s
